name: 'hash-files'
on:
  push:

env:
  # ======================================
  # CONFIG PRIVATE REPO (editable)
  # PATH_FOLDER = empty or name of folder
  # ======================================
  PATH_FOLDER: Xovi_Extensions
  PATH_HASHTABS: Xovi_Extensions/.hashtabs

  # ======================================
  # CONFIG PUBLIC REPO (editable)
  # ======================================
  NAME_PUBLIC_REPO: PepikVaio/reMarkable_Xovi_Extensions
  NAME_TOKEN: PUBLIC_REPO_TOKEN

  # ======================================
  # CONFIG (editable)
  # COMMIT_MESSAGE = empty or message
  # ======================================
  COMMIT_MESSAGE: ""
  IGNORE_HIDDEN: true

jobs:
  main:
    name: 'Update the public-facing repo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: ${{ env.PATH_FOLDER || '' }}
          sparse-checkout-cone-mode: true
      - uses: PepikVaio/reMarkable_Qmldiff-hasher-action@main
        name: 'Run the action'
        with:
          source_root: ${{ env.PATH_FOLDER }}
          hashtab_root: ${{ env.PATH_HASHTABS }}
          dest_repo_name: ${{ env.NAME_PUBLIC_REPO }}
          repo_access_token: ${{ secrets[env.NAME_TOKEN] }}
          commit_message: ${{ env.COMMIT_MESSAGE }}
